== Descentralización usando Blockchain

En los últimos años, Bitcoin y muchas otras criptodivisas han emergido con fuerza. No se trata solo de monedas alternativas, son
una nueva forma de gestionar el sistema monetario de forma completamente descentralizada gracias a la tecnología de la cadena de 
bloques. Con esta tecnología, las reglas de gobierno son elaboradas en base a parámetros numéricos y cálculos matemáticos 
previamente informados a todos los miembros. No hay autoridades centrales o bancos centrales que posean gobernanza absoluta del 
sistema financiero. Se acabaron los intermediarios.

Este sistema es el fundamento de un creciente número de registros globalmente distribuidos llamados cadenas de bloques 
(Blockchain), el más grande de	 los cuales es Bitcoin.	

Aunque el aspecto tecnológico es complicado y la expresión «blockchain» suena rara, la idea es sencilla. Las cadenas de bloques 
nos permiten enviar dinero de manera directa y segura de	 una persona a otra sin pasar por un banco, una tarjeta de crédito o 
PayPal.

De una forma sencilla el sistema Bitcoin, la tecnología blockchain de primera generación, que iremos conociendo en este libro, 
que ahora se percibe como una posible  moneda electrónica global, no es otra cosa que una base de datos que se halla distribuida 
entre diferentes participantes, protegida criptográficamente y organizada en bloques de transacciones relacionados entre sí 
matemáticamente.

Expresado de forma más breve, es una base de datos descentralizada que no puede ser alterada. También se puede definir como una 
base de datos compartida que funciona como un libro de registro de operaciones de compra y venta, como los libros contables, 
pero que además, como veremos mas adelante, incorpora innovadores mecanismos para interaccionar con la comunidad,  que es la que 
elige soportar y usar este sistema.


=== Concepto: Descentralización

Una de las razones por las cuales se percibe que la tecnologia que  subyace bajo el sistema de Bitcoin, es revolucionaria,  por 
ser un sistema descentralizado, sin ninguna autoridad central.

La idea de la descentralización es que, al igual que ocurre en un red peer to peer,(P2P) o lo que es lo mismo, una red de igual a 
igual, de personas o de ordenadores, donde nadie tiene un control central de lo que ocurre, nadie puede dictar; no es un régimen 
autoritario y se elimina toda jerarquía e intereses particulares, e intervenciones arbitrarias

Los sistemas de igual a igual han demostrado a lo largo de su corta historia, que tienen interesantes aplicaciones tales como 
compartición de ficheros, distribución de contenidos,  y protección de la privacidad.

Sin embargo, los sistemas centralizados, a los que estamos acostumbrados, tienen puntos de fallo. Es decir, si un punto que se 
encuentra en lo mas elevado de la jerarquía falla, el sistema puede fallar o colapsar de forma completa.

En cambio, en los sistemas descentralizados eso no ocurre, ya que el modelo es horizontal, y si un punto falla, ya hay otros 
muchísimos nodos al mismo nivel, peer to peer,  de forma que no se pierde nada. Es decir, en una sociedad descentralizada se 
intenta que todos seamos prescindibles y que no podamos hacer un daño perjudicial al resto de la sociedad, aunque queramos. Se 
brinda al sujeto una individualidad y libertad propia acorde a su voluntad. Todo se basa en el consenso y la actitud activa. 
Todos somos productores y consumidores de recursos, a la vez, al mismo nivel.


Al unirse a un sistema de igual a igual, los usuarios cambian sus ordenadores en nodos del sistema que son iguales con respecto a 
sus derechos y roles.
Aunque los usuarios pueden diferir con respecto a los recursos que contribuyen, todos los nodos en el sistema tienen la misma 
capacidad funcional y responsabilidad. 

Por lo tanto, los ordenadores de todos los usuarios son proveedores y consumidores de recursos. La descentralización permite 
crear organizaciones en las que todos sus miembros son propietarios de los productos y servicios que estos ofrecen.

Esto va a  permitir, en el presente o en el futuro, lo que se ha denominado DAO (Organizaciones Autónomas Descentralizadas), 
organizaciones de gestion descentralizadas, por acuerdos programados entre todos los que contribuyen y participan en la 
organización
(Ver mas abajo en “Ethereum: Supercomputacion descentralizada)
