Entonces vale la pena preguntar: 

== ¿Qué es una cadena de bloques o Blockchain?

La idea básica de una cadenas de bloques es mantener un registro, libro de contabilidad o base de datos distribuida de cierto tipo de información a lo largo del tiempo y que resista especialmente modificaciones malintencionadas. Cada uno de esos bloques contiene la información codificada de una transacción en la red. Normalmente se emplea en transacciones de tipo financiero, de modo que la cadena de bloques es una especie de «libro de contabilidad público incorruptible»: la información más reciente depende de que toda la información del pasado se encuentre intacta. Esto evita la manipulación y sirve como protección ante fraudes. En Bitcoin, por ejemplo, se usa para saber quién paga qué a quién, de modo que no se pueda negar haber recibido o pagado algo.

La Blockchain es el libro público de todas las transacciones de Bitcoin que alguna vez han sido ejecutadas. Está en constante crecimiento ya que los mineros le agregan nuevos bloques (cada 10 minutos) a registrar las transacciones más recientes. Los bloques se agregan a la cadena de bloques en en una linea de tiempo, con orden cronológico. 

Cada nodo completo (es decir, cada ordenador conectado a la red Bitcoin utilizando un cliente que realiza la tarea de validar y retransmitir transacciones) tiene una copia de la cadena de bloques, que se descarga automáticamente cuando el minero se une a la red de Bitcoin. El blockchain tiene información completa sobre las direcciones y saldos desde el bloque de génesis (las primeras transacciones jamás ejecutadas) al bloque más recientemente completado.

La cadena de bloques, como libro público,  significa que es fácil para consultar con cualquier explorador de bloques (como https://blockchain.info/) para las transacciones asociadas con una dirección particular de Bitcoin, por ejemplo, puedes buscar  tu propio monedero o dirección para ver la transacción en la que recibes  tu primer Bitcoin.

Blockchain es visto como la principal innovación tecnológica de Bitcoin porque se erige como un mecanismo de prueba "sin confianza" de todas las transacciones en la red. Usuarios puede confiar en el sistema del libro público almacenado en todo el mundo, en muchas décadas diferentes. Nodos descentralizados mantenidos por "contadores mineros", en lugar de tener que establecer y mantener la confianza con la contraparte de la transacción (otra persona) o un tercero intermediario del partido (como un banco).

Blockchain, subyace como la arquitectura para un nuevo sistema de las transacciones descentralizadas sin confianza. Es la innovación clave. Como ya hemos visto la cadena de bloques permite, des-intermediación y descentralización de todas las transacciones de cualquier tipo entre todos las partes a nivel mundial


=== Transferencia del valor

Las tecnologías consensuadas descentralizadas proporcionan, por primera vez, una forma para que un usuario de Internet transfiera una propiedad digital única a otro usuario de Internet, de modo que la transferencia garantizada sea segura, pública e irrefutable. De adoptarse, estas tecnologías podrían transformar fundamentalmente la forma en que opera el mundo, introduciendo una gama de eficiencias para el comercio, las finanzas, las leyes y los seguros, y permitiendo la creación de la próxima generación de la World Wide Web, lo que ya se denomina como Web3.

Podemos hablar de lo que se ha llamado el internet del valor: Las cadenas de bloques no solo sirven para transmitir información sino para transmitir valor porque :

 – Disponen de una unidad de cuenta
 – Son inmutables
 – Son seguras
 – Funcionan sin autoridad central y sin terceros de confianza
 – Tienen un mecanismo de consenso

Por lo tanto, la cadena de bloques puede ser utilizado para cualquier forma de registro de activos, inventario e intercambio, incluidas todas las áreas de finanzas, economía y dinero; activos tangibles (propiedad física); y activos intangibles (votos, ideas, reputación, intención, datos de salud, etc.).

“#The Bitcoin protocol and network today is that foundational layer. It is a value transfer network.Beyond that, it is a core, backbone security service securing contracts, physical and digital property, equities, bonds, robot AI and an enormous wave of applications which have not yet been conceived.” 

Jeff Garzik, Bitcoin core developer and CEO, Dunvegan Space Systems

