== Tipos de Blockchain: Público, Privado e Híbrido 

Existen tres tipos: 
-Públicas
-Privadas 
-Híbridas.

=== Blockchains públicas

Los ejemplos más conocidos de Blockchains públicas son Bitcoin y Ethereum. Una Blockchain pública es accesible a cualquier usuario en el mundo. Lo único que se necesita es un ordenador y una conexión a Internet.
El problema central a resolver por el Blockchain publico es lograr y mantener la integridad en un sistema punto a punto puramente distribuido  que se compone de un número desconocido de pares con confiabilidad desconocida.

Bitcoin, por primera vez, resuelve este problema, y lo hace de manera segura, o muy segura. Por un lado, una de las principales fortalezas de su seguridad viene de la aplicación de robustos sistemas criptográficos, que ofrece un nivel de seguridad superior a los más avanzados de defensa de servidores, por otro lado plantea un nuevo paradigma en la forma de estructurar su arquitectura operativa, más allá de la estructura cliente servidor (centralizada) muy vulnerable o de los modelos Cloud (distribuido) que también comienzan a dar señales de lentitud en respuesta a desafíos de  seguridad,


=== Blockchains privadas

Una Blockchain privada, a diferencia de una Blockchain pública, no está abierta al público, sino que solo se puede acceder a ella por invitación. Las Blockchains privadas son más nuevas que las Blockchains públicas y pueden ser muy diferentes las unas a las otras y en algunos casos es incluso cuestionable que se pueda hablar de Blockchain para algunas de las soluciones que se conocen en el mercado. Algunas de las más famosas son Hyperledger (de la Fundación Linux), R3 (un consorcio de bancos internacionales para desarrollar soluciones bancarias de blockchain privada) o Ripple (un protocolo para facilitar las transferencias internacionales de dinero).

=== Blockchains híbridas

Las Blockchain híbridas son una combinación de las públicas y privadas. En una Blockchain híbrida los nodos participantes son invitados, pero todas las transacciones son públicas. 
Aquí, el proceso de validación de consenso puede ser controlado por personas u organizaciones preseleccionadas, como un consorcio de instituciones financieras o los clientes de una empresa.

Eso quiere decir que los nodos participan en el mantenimiento y seguridad de esta blockchain, pero que todas las transacciones son visibles para usuarios en todo el mundo y que no tienen que conocer el contenido de la Blockchain, a diferencia de las blockchains privadas en la cual las transacciones son privadas también. 
Algunos ejemplos de Blockchains híbridas son BigchainDB (un proveedor de tecnología Blockchain) o Evernym, una blockchain híbrida que quiere facilitar la gestión de la Identidad Digital Soberana (ltSelf Sovereign Identity). Otro ejemplo de Sistema híbrido o de consorcio, es el consorcio español de grandes empresas, Alastria. 

En general, el derecho de leer la Blockchain asociada puede ser público o restringido a los participantes. Estos sistemas son considerados parcialmente descentralizados. Se puede requerir que la identidad de los usuarios se conforme para conocer su negocio ("KYB") o conocer los procedimientos de su cliente ("KYC"). Si estos sistemas necesitan una moneda integrada para proporcionar incentivos dependería del grado de confianza, que a su vez dependerá del grado de descentralización.

